spring:
  application:
    name: console-availability-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS